import torch
import torch.nn as nn
from torch.nn import functional as F
import os 
import glob
import numpy as np
import pickle
import time

torch.set_float32_matmul_precision('high')

# === 1. 超参数设置 ===
batch_size = 32      # 每次并行处理多少个序列
block_size = 256     # 句子的最大长度 (Context Window)
max_iters = 10000     # 总训练步数
eval_interval = 1000  # 每隔多少步评估一次
learning_rate = 3e-4 # 学习率
device = 'cuda' if torch.cuda.is_available() else 'cpu' # GPU的强项: 进行海量的矩阵运算
eval_iters = 200     # 在评估损失的estimate_loss中使用，表示评估平均损失时的采样样本数
n_embd = 512         # 词向量维度
n_head = 8           # 多头注意力的头数
n_layer = 8          # Transformer Block 的层数
dropout = 0.1        # 防止过拟合的丢弃率：在每一次训练步骤中，程序会随机选中 20% 的神经元，并强行把它们的输出变成 0。
temperature = 0.8    # 温度，低温稳健， 高温创新
manual_seed = 1337   # 设定随机种子，使得程序每次运行时生成的初始随机数都是一样的，使得在不同设备上能得到相同的结果
# =====================

torch.manual_seed(manual_seed) 
data_dir = "E:/Programs/WeChatData/texts/*.txt"

# === 2. 数据读取与预处理 ===
# generated by gemini
# 1. 加载元数据 (词表映射关系)
meta_path = 'meta.pkl'
if os.path.exists(meta_path):
    with open(meta_path, 'rb') as f:
        meta = pickle.load(f)
    stoi, itos = meta['stoi'], meta['itos']
    vocab_size = meta['vocab_size']
    encode = lambda s: [stoi[c] for c in s]
    decode = lambda l: ''.join([itos[i] for i in l])
    print(f"成功加载词表，大小为: {vocab_size}")
else:
    raise FileNotFoundError("未找到 meta.pkl，请先运行预处理脚本！")

# 2. 加载训练好的二进制数据
# 使用 np.memmap 是为了不在启动时瞬间撑爆内存，而是按需读取
train_data = np.memmap('train.bin', dtype=np.uint16, mode='r')
val_data = np.memmap('val.bin', dtype=np.uint16, mode='r')

print(f"数据加载完成！训练集: {len(train_data)/10000:.2f}w 字符, 验证集: {len(val_data)/10000:.2f}w 字符")

# 3. 适配 get_batch 函数
# 因为数据现在是 numpy 格式，我们需要在 get_batch 里将其转为 torch.tensor
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    
    # 转换为 torch.long (即 int64)，这是模型层要求的输入格式
    x = torch.stack([torch.from_numpy(data[i:i+block_size].astype(np.int64)) for i in ix])
    y = torch.stack([torch.from_numpy(data[i+1:i+block_size+1].astype(np.int64)) for i in ix])
    
    x, y = x.to(device), y.to(device)
    return x, y

# 本质: 
# model.eval()
# with torch.no_grad(): ...
@torch.no_grad() # 装饰器的作用：在进入函数前先关闭梯度记录，退出时又重新开启
def estimate_loss():
    '''评估损失'''
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

# === 3. 模型组件定义 ===

# ========== 由于MultiHeadAttention里已经实现了多头同时生成在一个矩阵里，并行处理
# 因此Head类可删去， 这里仅保留注释作为思路参考

# class Head(nn.Module):
#     '''单头注意力 : '''
#     def __init__(self, head_size):
#         super().__init__() # 调用父类初始化，激活Pytorch的管理功能
#         self.key = nn.Linear(n_embd, head_size, bias=False)
#         self.query = nn.Linear(n_embd, head_size, bias=False)
#         self.value = nn.Linear(n_embd, head_size, bias=False)
#         # 在nn.Module的__init__中定义线性层时，它们的参数会被注册为Parameters, 意味着优化器在训练时会更新它们
        
#         # self.register_buffer : 专门存放"非参数，但属于模型一部分"的数据，不会更新，但也会随着模型保存、搬到显卡上
#         # self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        
#         # 创建一个具体的层，用来执行丢弃任务
#         # nn.Dropout(dropout_rate)是nn.Module提供的功能层,
#         # 调用model.train()时：nn.Module会通知所有dropout层：开始工作
#         # 调用model.eval()时：会停止丢弃，准备预测。
#         self.dropout = nn.Dropout(dropout)
#         # 底层逻辑：1. 生成掩码，如对于(1, 1, 1, 1), 丢弃率0.25, 则产生掩码(随机) (0, 1, 1, 1)
#         # 2. 丢弃 ： (1, 1, 1, 1) * (0, 1, 1, 1) = (0, 1, 1, 1)
#         # 3. 缩放(使得模长不变) 所有数值除以(1 - p)
 
#     def forward(self, x):
#         B, T, C = x.shape # Batch, Time(Tokens, 有多少单词), Channels(向量维度)
#         q = self.query(x) # (B,T,head_size)
#         k = self.key(x)   # (B,T,head_size)
#         v = self.value(x)
    
#         # 这部分调用更加高效的 torch.nn.functional.scaled_dot_product_attention (SDPA) 代替
#         # PyTorch 的 SDPA 函数将下面所有步骤（缩放、掩码、Softmax、Dropout、矩阵乘法）封装成了一个极其优化的底层算子。
      
#         # wei = q @ k.transpose(-2, -1) * C**-0.5 # k.transpose(-2, -1) : (B, head_size, T), 只转置最后两个维度进行矩阵相乘
#         # wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # 掩码操作
#         # wei = F.softmax(wei, dim=-1) # wei : (B, T, T)， 结果wei(i, j)就表示词i与词j的相近程度(分数)
#         # wei = self.dropout(wei)      # 随机丢弃
#         # out = wei @ v # (B, T, T) * (B, T, head_size) = (B, T, head_size) 通过QKV学习修正后的特征矩阵
        
#         # is_causal=True 会自动处理 self.tril 那样的下三角掩码（GPT 必备）
#         out = F.scaled_dot_product_attention(
#             q, k, v,
#             # 注意力掩码，手动指定哪些位置不应该被关注，通常是与Q @ K^T 形状兼容的向量
#             attn_mask=None, 
#             # self.training : nn.Module自带的属性，标记模型此时是否处于训练模式
#             dropout_p=self.dropout.p if self.training else 0.0, 
#             # 因果掩码的开关，防止模型偷看
#             is_causal=True
#         )

#         # wei (B, T, T)：这是一个权重矩阵。对于 batch 中的每一行，它告诉我们：为了理解当前位置的词，我们需要对句子中其他位置的词付出多少“注意力” 。
#         # v (B, T, head_size)：这是每个词的“特征向量”
#         # 得到的out就是学习了上下文之后，表示了每个词的特征的矩阵
#         return out

# ==========================

class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        # self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)]) # 类似于Python的list， 但这是torch专用的，
        # 当模型调用.train()/.eval() 或者 .to(device) 时，会将操作递归地应用到nn.ModuleList中的元素

        # ======修改后======
        # 将所有头以及各自的Q,K,V生成合并成一起
        self.qkv_attn = nn.Linear(n_embd, 3 * n_embd, bias=False) # (B, T, 3 * n_embd)

        # self.proj : 将多头注意力分别处理数据并拼接得到的矩阵再进行一次处理，从而融合多头的数据特征
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # 拼接 n_embd // head_size 个 (B, T, head_size) 得到 (B, T, n_embd)
        # 这里是串行的、效率较低的写法，Python循环是串行的
        # out = torch .cat([h(x) for h in self.heads], dim=-1) 
        
        # 修改后的逻辑：关键是利用.view() 和 .transpose()将数据切分成多个头
        # ==============
        B, T, C = x.shape
        qkv = self.qkv_attn(x)

        # 拆分q, k, v
        q, k, v = qkv.split(n_embd, dim=2) # (n_embd, )

        # 变换形状
        k = k.view(B, T, n_head, C // n_head).transpose(1, 2)
        q = q.view(B, T, n_head, C // n_head).transpose(1, 2)
        v = v.view(B, T, n_head, C // n_head).transpose(1, 2)

        # 调用高效的 scaled_dot_product_attention
        out = F.scaled_dot_product_attention(
            q, k, v,
            is_causal=True,
            dropout_p=dropout if self.training else 0
        )

        # 还原形状, 并合并所有头
        # 在还原之前，还要先调用一个contiguous(), 是因为.view()处理的张量必须是在内存中连续存储的
        out = out.transpose(1, 2).contiguous().view(B, T, C)
        # ==============

        out = self.dropout(self.proj(out))
        return out

class FeedForward(nn.Module):
    '''前馈网络'''
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.GELU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        '''前向传播'''
        return self.net(x)

class Block(nn.Module):
    '''Transformer 块'''
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        # 先经过自注意力机制(Q/K/V)，获取词与词之间的联系。详细过程：
        # 1. 自注意力机制通过三个线性变换(矩阵乘法),将每个词投射到Q,K,V三个空间
        # 2. 算匹配度: weight = Q @ K^T 得到关系矩阵, weight(i, j) 表示"处理第i个词时，第j个词的重要性"。
        # 复习前面所说的，为了避免"偷看"，会将上三角的内容变为-inf，使得第i个词只能关注到前i个词。
        # 3. 归一化 + 残差连接
        x = x + self.sa(self.ln1(x))
        # 再通过前馈网络，其实就是一组线性层加上一个激活函数，来处理得到的信息
        # 自注意力机制实质上是加权组合，如果没有前馈网络的话就会变成简单的线性叠加，退化成线性回归，因此前馈网络是必要的。
        x = x + self.ffwd(self.ln2(x))
        return x

# === 4. 主模型类 ===

class NanoGPT(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd=n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

        self.apply(self._init_weights) # 权重初始化，显著加快前1000步的收敛
    # from AI
    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        '''idx: (batch_size, block_size), 代表每一批(共batch_size批)的每一组起始位置(共block_size个)的索引'''
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx) # 拿到(batch_size, tokens, n_embd),即原词表中提取的部分特征向量
        # torch.arange(T) ：生成一个从 0 到 T-1 的等差数列张量
        # device = device : 在Pytorch中，两个张量必须处在同一个设备上才能进行运算
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (tokens, n_embd)
        x = tok_emb + pos_emb # 加上位置张量，给输入增添了位置信息(运算采用广播机制)
        x = self.blocks(x)
        x = self.ln_f(x)
        # 解码，输出的logits(batch_size, tokens, vocab_size)
        # 对每一批(batch)的每个词(tokens), 长度为vocab_size 的向量表示词表中"下一个词"出现的概率
        logits = self.lm_head(x)

        if targets is None: # target 标准答案 (B, T)
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            # F.cross_entropy的输入是二维的：(样本数，类别数)
            loss = F.cross_entropy(logits, targets) # 计算交叉熵

        return logits, loss

    def generate(self, idx, max_new_tokens):
        '''idx : (B, T), B个起始点与其后面的共T个字符'''
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:] # 只选取最后block_size个词来预测下一个词
            # 好习惯：self(idx_cond)而不是forward(idx_cond), 虽然是实际上是调用了forward
            logits, loss = self(idx_cond)

            # 引入温度采样法：把原始得分除以温度 T
            # 注意：temperature 需要在函数参数里定义，比如设定默认值为 1.0
            logits = logits[:, -1, :] # (B, 1, n_embd)， 取最后一个词的预测结果，也就是预测出来的下一个词的可能性
            logits = logits / temperature

            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1) # 为每个词根据概率分布抽取下一个词(而不是直接选择概率最高的词)
            idx = torch.cat((idx, idx_next), dim=1) # 把抽中的新词拼接在旧序列的后面
        return idx # (B, T + max_new_tokens)， 因为循环了max_new_tokens次，每次拼接一个词

# === 5. 实例化与训练 ===

# 保存函数：
def save_checkpoint(model, optimizer, iter, loss, filename="ckpt.pt"):
    checkpoint = {
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'iter': iter,
        'loss': loss,
        'vocab_size': vocab_size,
    }
    # 1. 保存一个最新的（用于断点续传）
    torch.save(checkpoint, "ckpt_last.pt")
    
    # 2. 每隔一定步数，保存一个永久备份
    if iter % 1000 == 0:
        torch.save(checkpoint, f"CheckPoint/ckpt_iter_{iter}.pt")
        
    # 3. 只有当 Loss 创下新低时，保存一个“最佳”版本
    # (这需要你在外部维护一个 best_loss 变量)
    print(f"--> 已保存步数: {iter}")

def load_checkpoint(model, optimizer, filename="ckpt.pt"):
    if os.path.exists(filename):
        print(f"发现存档 {filename}，正在恢复...")
        # map_location 确保了即使是在 CPU 上也能加载 GPU 训练的模型
        checkpoint = torch.load(filename, map_location=device)
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        start_iter = checkpoint['iter']
        print(f"成功恢复！将从第 {start_iter} 步继续训练。")
        return start_iter
    else:
        print("未发现存档，将从头开始训练。")
        return 0

if __name__ == "__main__":

    torch.cuda.empty_cache() # 清除显存缓存

    model = NanoGPT()
    m = model.to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=0.05) # 设置正则化系数防止过拟合

    # 尝试加载进度
    current_iter = load_checkpoint(model, optimizer=optimizer)
    
    print(f"开始训练！按 Ctrl+C 可以随时停止并查看生成效果。\n 设备：{device}")
    start_time = time.time()

    try:
        # 训练25MB数据集时，为例避免显存不足，使用混合精度训练法(Automatic Mixed Precision, AMP)
        # 默认情况下，PyTorch 使用 float32（32位浮点数）进行计算。
        # 混合精度会让模型在计算某些对精度不敏感的算头（如线性层、卷积）时使用 float16
        scaler = torch.amp.GradScaler('cuda')


        for iter in range(current_iter, max_iters):
            # 定期评估并保存
            if iter % eval_interval == 0:
                losses = estimate_loss()
                print(f"步数 {iter}: 训练集 Loss {losses['train']:.4f}, 验证集 Loss {losses['val']:.4f}")

                # 自动保存训练进度
                save_checkpoint(model, optimizer, iter, losses['val'])

            xb, yb = get_batch('train')

            # 1. 使用 autocast 上下文
            with torch.amp.autocast(device_type='cuda', dtype=torch.float16):
                logits, loss = model(xb, yb)   

            optimizer.zero_grad(set_to_none=True)

            # 2. 使用 scaler 来缩放损失并回传梯度
            scaler.scale(loss).backward()
            
            # 3. scaler.step 代替 optimizer.step()
            scaler.step(optimizer)
            
            # 4. 更新缩放器
            scaler.update()


    except KeyboardInterrupt:
        print("\n" + "="*30)
        print("检测到手动中断！正在保存当前进度并生成结果...")
        try:
            # 尝试获取当前循环的 loss，如果还没产生，就用 0.0 代替
            current_loss = loss.item() if 'loss' in locals() else 0.0
            save_checkpoint(model, optimizer, iter, current_loss)
        except Exception as e:
            print(f"保存失败: {e}")

    end_time = time.time()
    total_time = end_time - start_time

    # === 6. 生成结果测试 ===
    print(f"\n共耗时约 {total_time // 60}minutes, 正在生成样本文本 ---")
    context = torch.zeros((1, 1), dtype=torch.long, device=device)
    print(decode(m.generate(context, max_new_tokens=1500)[0].tolist()))
