# generated by gemini
import numpy as np
import os
import glob
import pickle

data_dir = "E:/Programs/WeChatData/texts/*.txt"
file_paths = glob.glob(data_dir)
all_text = []

print(f"检测到 {len(file_paths)} 个文本文件，正在合并数据...")

for path in file_paths:
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        all_text.append(f.read())

text = "\n".join(all_text) 
print(f"数据读取完成，总字符数: {len(text) / 10000:.2f}w")

# 1. 建立词表
chars = sorted(list(set(text)))
vocab_size = len(chars)
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }

# 2. 转换并保存
ids_array = np.array([stoi[c] for c in text], dtype=np.uint16)

# 3. 这里直接切分并保存，训练脚本加载时会非常清爽
n = int(0.9 * len(ids_array))
train_data = ids_array[:n]
val_data = ids_array[n:]

train_data.tofile('train.bin')
val_data.tofile('val.bin')

# 4. 保存元数据
with open('meta.pkl', 'wb') as f:
    pickle.dump({
        'chars': chars, 
        'stoi': stoi, 
        'itos': itos,
        'vocab_size': vocab_size
    }, f)

print(f"预处理完成！\n- 词表大小: {vocab_size}\n- 训练集大小: {len(train_data)/10000:.2f}w 字符\n- 验证集大小: {len(val_data)/10000:.2f}w 字符")